### ISSUE TITLE
vendored imports are import the fullpath and not the vendored path

### ISSUE THREAD

**Issue by awalterschulze** [awalterschulze/goderive#16]
`github.com/bbb/alb/vendor/bla`

instead of

`bla`

**Comment by awalterschulze** [comment]
fixed

**Comment by guoshimin** [comment]
This was not fully fixed. I got import paths like "vendor/foo/bar". Should be "foo/bar". The fix didn't capture the case where vendor is the first segment in the path.

**Comment by awalterschulze** [comment]
Just for reference this was the fix
https://github.com/awalterschulze/goderive/commit/e63acc11d36efd92fa9bd3b99cf7f66a6a5b4ec3

Yes it seems I assume that it starts with a slash

**Comment by awalterschulze** [comment]
Good catch

**Comment by awalterschulze** [comment]
Could you try it now?

I just pushed a fix
https://github.com/awalterschulze/goderive/commit/e2f13388448e7b1f3791fe88e0945bee0582cb52

**Comment by guoshimin** [comment]
Nope, path now has an unwanted leading `/`

**Comment by awalterschulze** [comment]
And now?

**Comment by awalterschulze** [comment]
https://github.com/awalterschulze/goderive/commit/57020fc5ea6fb369de74968c4e540adf23388a05

**Comment by awalterschulze** [comment]
Sorry I'm a bit tired.

**Comment by guoshimin** [comment]
Works now! No need to apologize. Thank you for the quick turnaround. Goderive is awesome!

**Comment by awalterschulze** [comment]
Awesome. Glad you are enjoying it.  If you are using it in a project, it would be great to add that project to the users list, but no pressure.
Thanks for reporting :)
